name: flutter_syntax_view
description: A static syntax highlighter widget which highlights code text according to the programming language syntax using native Dart code.
version: 4.1.1
homepage: https://github.com/baderouaich/flutter_syntax_view

environment:
  sdk: '>=3.3.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  string_scanner: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
